# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 100

checkpoint:
  save_interval_updates: 5000
  keep_interval_updates: 200
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 320000
  min_sample_size: 32000
  normalize: true

dataset:
  num_workers: 6
  max_tokens: 1200000
  skip_invalid_size_inputs_valid_test: true
  update_epoch_batch_itr: true

distributed_training:
  distributed_world_size: 128
  distributed_no_spawn: true
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 0]

optimization:
  max_update: 400000
  lr: [0.0005]
  clip_norm: 25.0

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 5000

model:
  _name: wav2vec_S
  quantize_targets: true
  extractor_mode: layer_norm
  layer_norm_first: true
  final_dim: 768
  latent_temp: [2.0,0.1,0.999995]
  encoder_layerdrop: 0.00
  dropout_input: 0.1
  dropout_features: 0.1
  dropout: 0.0
  attention_dropout: 0.1
  conv_bias: true

  encoder_layers: 24
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  encoder_attention_heads: 16

  feature_grad_mult: 1.0
  max_positions: 8000

  main_context: 16
  right_context: 8
  context_type: sampling
  load_pretrained_model_from: ""
  pos_type: "sin"
  mask_length: 10
  mask_prob: 0.65
  mask_selection: 'static'
  mask_other: 0
  no_mask_overlap: False
  mask_min_space: 1
  mask_channel_length: 10
  mask_channel_prob: 0
  mask_channel_selection: static
  mask_channel_other: 0
  no_mask_channel_overlap: False
  mask_channel_min_space: 1
  conv_feature_layers: '[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512,2,2)] * 2'
